services:
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: pnpm run start:dev auth
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app
      # - /usr/src/app/node_modules
    networks:
      - sleepr-net
    env_file:
      - ./apps/auth/.env

  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: pnpm run start:debug reservations
    ports:
      - '3000:3000'
      - '9229:9229'
    volumes:
      - .:/usr/src/app
      # - /usr/src/app/node_modules
    networks:
      - sleepr-net
    env_file:
      - ./apps/reservations/.env

  payments:
    build:
      context: .
      dockerfile: ./apps/payments/Dockerfile
      target: development
    command: pnpm run start:dev payments
    env_file:
      - ./apps/payments/.env
    volumes:
      - .:/usr/src/app
    networks:
      - sleepr-net

  notifications:
    build:
      context: .
      dockerfile: ./apps/notifications/Dockerfile
      target: development
    command: pnpm run start:dev notifications
    env_file:
      - ./apps/notifications/.env
    volumes:
      - .:/usr/src/app
    networks:
      - sleepr-net

  mongo:
    image: bitnami/mongodb:5.0
    volumes:
      - 'mongodb_data:/bitnami/mongodb'
    ports:
      - 27017:27017
    networks:
      - sleepr-net

networks:
  sleepr-net:
    name: sleepr-net
    driver: bridge

volumes:
  mongodb_data:
